### ISSUE TITLE
New release of SimSinter

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/SimSinter#19]
I need to make some changes to SimSinter.  I can build it for myself, but we need to get the automated build going for distribution.

I was able to get it to build with VS 2017.

**Comment by ksbeattie** [comment]
@boverhof I'd like to try working with you on getting this done on AppVeyor.  Do you think that's possible?

**Comment by boverhof** [comment]
release created:
https://github.com/CCSI-Toolset/SimSinter/releases/tag/2.1.0
