### ISSUE TITLE
SimSinter 2.1.0 Release Install and Test

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/SimSinter#25]
# Description
Check the installer, install SimSinter, and test against FOQUS.

- [x] Check Installer menus, including new license
- [x] Install SimSinter
- [x] Install new TurbineLite 2.3.0
- [x] Test with FOQUS (needs new TurbineLite)
- [ ] Test SinterGUI (needs new TurbineLite)

**Comment by boverhof** [comment]
@ksbeattie I have fixed `master` and now it is building an installer that will work.   

I also update the download `prerelease` for both SimSInter and Turbine.

**Comment by ksbeattie** [comment]
Related to: #26

**Comment by ksbeattie** [comment]
Blocked by #25

**Comment by boverhof** [comment]
Closing, created new SimSinter 2.1.0.1 and TurbineLite 2.3.0.1 that needs testing.
