### ISSUE TITLE
Can binary Aspen files be replaced with text backups?

### ISSUE THREAD

**Issue by vchendrix** [CCSI-Toolset/SimSinter#3]
The following binary Aspen files are included.  
**Can binary Aspen files be replaced with text backups?**

* Master/test/DynamicTest/AM_BFB/propsplus.aprpdf:	data
* Master/test/DynamicTest/AM_BFB/snapshot.bak:	data
* Master/test/DynamicTest/AM_BFB/tasksnap.bak:	data

**Comment by fsoepyan** [comment]
According to @eslickj, the answer is "no", unless there are other ones besides the ones on the list.
