### ISSUE TITLE
Remove gPROMS support from SimSinter

### ISSUE THREAD

**Issue by kbuma** [CCSI-Toolset/SimSinter#44]
The developers do not have access to gPROMS thus cannot test the functionality.

If the community does not have any critical use cases for this we propose removing this functionality from the code base in order to reduce the cost of maintenance of SimSinter.

**Comment by ksbeattie** [comment]
For the Sept release, this will be deprecated in the release notes (at least).

**Comment by ksbeattie** [comment]
Will target this for April, or release past March.
