### ISSUE TITLE
Test whether AWS FOQUS Cloud works with new SimSinter 

### ISSUE THREAD

**Issue by kbuma** [CCSI-Toolset/SimSinter#51]
Test whether AWS FOQUS Cloud works with new SimSinter 

- [ ] What/how needs to be tested here?

**Comment by ksbeattie** [comment]
This fits with FOQUS Milestone: [EY23.4.1.N: Improvements to single-user FOQUS Cloud usability and documentation](https://github.com/CCSI-Toolset/FOQUS/milestone/41)

**Comment by kbuma** [comment]
We discussed in weekly meeting and decided that this will go to the next milestone.

**Comment by ksbeattie** [comment]
@boverhof is working on this in https://github.com/CCSI-Toolset/FOQUS/issues/1224
