### ISSUE TITLE
Sign next release with a trusted developer certificate to avoid Windows warning when running installer.

### ISSUE THREAD

**Issue by kbuma** [CCSI-Toolset/SimSinter#52]
We'd like to avoid Windows popping up a warning when running the SimSinter installer. In order to do stop that we will sign next release with a trusted developer certificate.

**Comment by kbuma** [comment]
Got access to the Azure key vault with the LBL signing certificate. Verified that can now sign using AzureSignTool and have SimSinter installer run as Windows trusted developer software.

**Comment by ksbeattie** [comment]
Sounds like we will need this also for TurbineLite.

**Comment by kbuma** [comment]
That should not be a problem as all this does is sign the existing
installer.
